import { useState } from 'react';
import Head from 'next/head';
import VideoRecognizer from '@/components/VideoRecognizer';
import ImageRecognizer from '@/components/ImageRecognizer';

export default function Home() {
  const [mode, setMode] = useState("video");
  return (
    <>
      <Head>
        <title>read-video-nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className='title'>
          <h2 className='title-text'>Hello World for Nextjs</h2>
          <img className='title-logo' src="/next.svg" alt="logo"></img>
        </div>
        <div className='top-btns'>
          <button onClick={()=>{setMode("video")}} style={{backgroundColor: mode === "video" ? "rgb(255, 174, 55)" : "#fff"}}>VideoRecognizer</button>
          <button onClick={()=>{setMode("image")}} style={{backgroundColor: mode === "image" ? "rgb(255, 174, 55)" : "#fff"}}>ImageRecognizer</button>
        </div>
        { mode === "video" ? <VideoRecognizer /> : <ImageRecognizer /> }
      </main>
    </>
  )
}
